FROM node:20-alpine AS builder
RUN apk add --no-cache python3 make g++
WORKDIR /app

# install deps and build
COPY package.json package-lock.json* ./
COPY . .
# use npm ci for reproducible builds
RUN npm ci --prefer-offline --no-audit --progress=false
RUN npm run build

FROM nginx:stable-alpine AS web
COPY --from=builder /app/dist/public /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
